language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - jruby
  - rbx
gemfile:
  - gemfiles/active_record_31.gemfile
  - gemfiles/active_record_32.gemfile
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby
  fast_finish: true
