language: ruby
script: "bundle exec rake test"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - ruby-head
  - jruby
  - rbx
gemfile:
  - gemfiles/active_record_40.gemfile
  - gemfiles/active_record_41.gemfile
  - gemfiles/active_record_42.gemfile
  - gemfiles/active_record_50.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - rvm: jruby
  fast_finish: true
