language: ruby

before_install:
  - rvm get head
  - gem install bundler

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - jruby
  - jruby-9.1.0.0
  - rbx

matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby
    - rvm: jruby-9.1.0.0
  fast_finish: true
